project:
  type: website
  output-dir: docs

website:
  title: "Emma Getz"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - project.qmd
      - resources.qmd
    
    tools:
      - icon: 
        href: 
      - icon: github
        href: https://github.com/emmagetz/emmagetz.github.io
      - icon: linkedin
        href: https://www.linkedin.com/in/emma-getz-7aa30821b
    
        menu:
          - text: Source Code
            href: https://github.com/emmagetz
          - text: Report a Bug
            href: https://github.com  

format:
  html:
    theme: morph  # flatly, litera, lumen, lux, minty, pulse, sandstone, zephyr, quartz, yeti, cosmo, sketchy
    css: styles.css
    toc: true

execute: 
  freeze: auto

