---
title: "Projects"
---

### Academic Research Projects
* [Departmental Honors Project Thesis Prospectus](./files/thesisprospectus)
* [Data Analysis using R - Analyzing Global Trends in Maternal Mortality](./mm/maternalmortality.qmd)
* [Epidemiology Honors Report - Alcohol Consumption Trends Among Adults in the United States and, D.C.](./files/PH4200honors.pdf)
* [Data Analysis using Stats IQ - Impact of Student Employment on Extracurricular Engagement](./files/3330FinalPosterGetz.pdf)

### Applied Public Health Projects
* [After-Action Report Template for Hurricane Helene](./files/AAR.pdf)
* [Homelessness Calendar -  Hospitality House](https://www.canva.com/design/DAF2CpuL6vA/QM2BphMKItOvaENTzcwzvw/view?utm_content=DAF2CpuL6vA&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel)
* [Sexual Violence Campaign Communications Infographic](https://www.canva.com/design/DAGCmkSDvUo/jdVqgywZFtncj_PrlBKtzA/view?utm_content=DAGCmkSDvUo&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel)
* [Maternal Health Intervention Plan - Maternal Exercise Program to Coosa County](Plan3800.pdf)

### Extracurricular Projects 
* [The Appalachian Portfolio - Graphics](https://theappalachianonline.com/staff_name/emma-getz/)
* [My Small Business - EmmaLinaLino](https://www.instagram.com/emmalinalino/)
