---
title: "Combining Data Frames Questions 1-3"
format: revealjs
editor: visual
author: "Emma Getz"
---

## Question 1

**Question:** "Take a look at the three data frames - `happy`, `happy_join_one`, and `happy_full` **Answer:** To learn more about these data frames, I used the `glimpse` function.

`glimpse(happy)`

`glimpse(happy_join_one)`

`glimpse(happy_full)`

## Question 2

**Question:** Combine `happy` and `happy_join_one` by row. **Answer:** The function I used to combine `happy` and `happy_join_one` by row is as follows:

`bind_rows(happy, happy_join_one)`

## Question 3

**question:** Combine `happy` and `happy_join_one` by column. **answer:** To answer this question, I first had to check if `happy` and `happy_join_one` had equal numbers of rows. I did this by using the function below:

`nrow(happy) == nrow(happy_join_one)`

Then, after finding that that function equals `TRUE` and that they do have the same numbers of rows, to combine `happy` and `happy_join_one` by columns I used the following function :

`bind_cols(happy, happy_join_one)`
